### ISSUE TITLE
Stations above one another cause an error

### ISSUE THREAD

**Issue by bakert** [johnwalley/d3-tube-map#15]
This data file will fail with

```
Error: <path> attribute d: Expected number, "Mundefined,undefi…".
(anonymous) @ d3.v5.js:1211
selection_each @ d3.v5.js:1176
selection_attr @ d3.v5.js:1233
drawLines @ d3-tube-map.js:556
(anonymous) @ d3-tube-map.js:502
selection_each @ d3.v5.js:1176
map @ d3-tube-map.js:442
selection_call @ d3.v5.js:1140
(anonymous) @ index.html:39
Promise.then (async)
(anonymous) @ index.html:37
```

```
{
  "stations": {
    "Central": {
      "name": "Central",
      "label": "Central"
    },
    "Roosevelt": {
      "name": "Roosevelt",
      "label": "Roosevelt"
    }
  },
  "lines": [
    {
      "name": "Green",
      "label": "Green",
      "color": "#00974C",
      "shiftCoords": [0, 0],
      "nodes": [
        {
          "coords": [0, 1],
          "name": "Central",
          "labelPos": "W"
        },
        {
          "coords": [0, 2],
          "name": "Roosevelt",
          "labelPos": "E"
        }
      ]
    }
  ]
}
```

If you change the `coords` of Roosevelt to `[1, 2]` then a map will be drawn and there will be no error.

Any idea what I'm doing wrong?

**Comment by johnwalley** [comment]
Thanks for providing the data to reproduce the error. It's definitely a bug and not something you're doing wrong.

If I had to guess it would be that the linear scales I create go wrong if all the stations have the same x values. Specifically, I use the result of `xScale(1) - xScale(0)` to define a 'length scale' for the map. 

I'll fix this up at the weekend and release a new version.

**Comment by johnwalley** [comment]
I've published a beta version: https://www.npmjs.com/package/d3-tube-map/v/0.8.0-beta.0 which fixes the specific error. The fix has the potential to affect some other parts of the rendering so I'm going to wait until I can test it in a bit more detail before releasing this properly.

https://github.com/johnwalley/d3-tube-map/pull/17

**Comment by bakert** [comment]
Works great on what I have so far. I can remove my spurious line endings!
:D Thanks,

Tom

**Comment by johnwalley** [comment]
Super. I'll leave this issue open as a reminder to convert this into a proper fix and release.

**Comment by johnwalley** [comment]
Live in v0.8.0
