### ISSUE TITLE
Lines not plotting

### ISSUE THREAD

**Issue by peterthirlby** [johnwalley/d3-tube-map#18]
Hi - the following test file won't plot the 'Commercial Line'

Running:

  <script src="https://d3js.org/d3.v4.js"></script>
  <script src="https://unpkg.com/d3-tube-map@latest/dist/d3-tube-map.js"></script>

d3.v5 won't produce anything, even with pubs.json

Many thanks in anticipation of your response

{
  "stations": {
    "BusEco": {
      "label": "Business Economics"
    },
    "Sustainability": {
      "label": "Sustainability"
    },
    "Productivity": {
      "label": "Productivity"
    }
    ,
    "Performance": {
      "label": "Performance"
    }
    ,
    "Finances": {
      "label": "Finances x"
    }
    ,
    "Investment": {
      "label": "Investment"
    }
    ,
    "Strategy": {
      "label": "Strategy"
    },
    "WorkDesign": {
      "label": "Work Design"
    },
    "WorkforceServices":{
      "label" : "workforce Services"
    },
    "Proposition":{
      "label" : "Proposition"
    }
  },
  "lines": [
    {
      "name": "Commercial Line",
      "label" : "Commercial Line",
      "color": "#FF0000",
      "shiftCoords": [0, 0],
      "nodes": [
        {
          "coords": [0, 0],
          "name": "BusEco",
          "labelPos": "S"
        }
        ,
        {
          "coords": [3, 2],
          "name": "Sustainability",
          "labelPos": "NW"          
        }
        ,
        {
          "coords": [6, 4],
          "name": "Productivity",
          "labelPos": "NW"          
        }
        ,
        {
          "coords": [9, 6],
          "marker": "interchange",
          "name": "Performance",
          "labelPos": "NW"          
        }
        ,
        {
          "coords": [12, 8],
          "name": "Finances",
          "labelPos": "NW"          
        }
        ,
        {
          "coords": [15, 10],
          "name": "Investment",
          "labelPos": "NW"          
        }
        ,
        {
          "coords": [18, 12],
          "name": "Strategy",
          "labelPos": "NW"          
        }
      
      ]
    }
    ,
    {
      "name": "Activity Line",
      "label" : "Activity Line",
      "color": "#2B8DBF",
      "shiftCoords": [0, 0],
      "nodes": [ 
        {
          "coords": [1, 6],
          "name": "WorkDesign",
          "labelPos": "W"          
        },
        {
          "coords": [9, 6],
          "marker": "interchange",
          "name": "Performance",
          "labelPos": "E"          
        }
      ]
    }  
    ,
    {
      "name": "Human Line",
      "label" : "Human Line",
      "color": "#85898A",
      "shiftCoords": [0, 0],
      "nodes": [ 
        {
          "coords": [33, 40],
          "name": "WorkforceServices",
          "labelPos": "W"          
        },
        {
          "coords": [33, 38],
          "name": "Proposition",
          "labelPos": "E"          
        }
      ]
    } 
  ]
}
    

![image](https://user-images.githubusercontent.com/37614533/55835680-65fc0700-5b14-11e9-8e1b-9172236fa305.png)

**Comment by johnwalley** [comment]
Thanks for getting in touch. I fully appreciate that the documentation on how to create the JSON to lay out a map is lacking so I'll describe the changes I think you need to make your layout work.

It's important that all lines run either vertically, horizontally or at 45 degrees. Anything else won't be recognised (won't even generate a warning at the moment). This is why you're not seeing the line drawn in the lower left. Assuming it's a straight line then we need to make sure the x and y positions of the stations always increase/decrease by the same amount.

The second limitation is that the position of the label, e.g. NW, NE, S also determines there the small rectangular tick mark goes. So for the Work Design station I'd recommend either N or S.

You should end up with something like:

<img width="708" alt="Screenshot 2019-04-11 at 16 50 10" src="https://user-images.githubusercontent.com/981531/55972062-a7a6c200-5c7a-11e9-9627-cf3faf23d2a0.png">

Modified JSON:

```
{
  "stations": {
    "BusEco": {
      "label": "Business Economics"
    },
    "Sustainability": {
      "label": "Sustainability"
    },
    "Productivity": {
      "label": "Productivity"
    },
    "Performance": {
      "label": "Performance"
    },
    "Finances": {
      "label": "Finances x"
    },
    "Investment": {
      "label": "Investment"
    },
    "Strategy": {
      "label": "Strategy"
    },
    "WorkDesign": {
      "label": "Work Design"
    },
    "WorkforceServices": {
      "label": "Workforce Services"
    },
    "Proposition": {
      "label": "Proposition"
    }
  },
  "lines": [
    {
      "name": "Commercial Line",
      "label": "Commercial Line",
      "color": "#FF0000",
      "shiftCoords": [0, 0],
      "nodes": [
        {
          "coords": [0, -3],
          "name": "BusEco",
          "labelPos": "NW"
        },
        {
          "coords": [3, 0],
          "name": "Sustainability",
          "labelPos": "NW"
        },
        {
          "coords": [6, 3],
          "name": "Productivity",
          "labelPos": "NW"
        },
        {
          "coords": [9, 6],
          "marker": "interchange",
          "name": "Performance",
          "labelPos": "SE"
        },
        {
          "coords": [12, 9],
          "name": "Finances",
          "labelPos": "NW"
        },
        {
          "coords": [15, 12],
          "name": "Investment",
          "labelPos": "NW"
        },
        {
          "coords": [18, 15],
          "name": "Strategy",
          "labelPos": "NW"
        }
      ]
    },
    {
      "name": "Activity Line",
      "label": "Activity Line",
      "color": "#2B8DBF",
      "shiftCoords": [0, 0],
      "nodes": [
        {
          "coords": [1, 6],
          "name": "WorkDesign",
          "labelPos": "N"
        },
        {
          "coords": [9, 6],
          "marker": "interchange",
          "name": "Performance",
          "labelPos": "E"
        }
      ]
    },
    {
      "name": "Human Line",
      "label": "Human Line",
      "color": "#85898A",
      "shiftCoords": [0, 0],
      "nodes": [
        {
          "coords": [33, 40],
          "name": "WorkforceServices",
          "labelPos": "W"
        },
        {
          "coords": [33, 38],
          "name": "Proposition",
          "labelPos": "E"
        }
      ]
    }
  ]
}
```

I do all my testing on d3 v5 so do let me know if you're still running into issues there.

**Comment by peterthirlby** [comment]
Many thanks for the reply, we got there in the end re the 45 degree issue

A handy tool

d3.v5 just doesn’t work for us, v4 does?

Thanks the suggestions

Peter


On 11 April 2019 at 16:57:25, John Walley (notifications@github.com) wrote:

Thanks for getting in touch. I fully appreciate that the documentation on how to create the JSON to lay out a map is lacking so I'll describe the changes I think you need to make your layout work.

It's important that all lines run either vertically, horizontally or at 45 degrees. Anything else won't be recognised (won't even generate a warning at the moment). This is why you're not seeing the line drawn in the lower left. Assuming it's a straight line then we need to make sure the x and y positions of the stations always increase/decrease by the same amount.

The second limitation is that the position of the label, e.g. NW, NE, S also determines there the small rectangular tick mark goes. So for the Work Design station I'd recommend either N or S.

You should end up with something like:

  

Modified JSON:

{
  "stations": {
    "BusEco": {
      "label": "Business Economics"
    },
    "Sustainability": {
      "label": "Sustainability"
    },
    "Productivity": {
      "label": "Productivity"
    },
    "Performance": {
      "label": "Performance"
    },
    "Finances": {
      "label": "Finances x"
    },
    "Investment": {
      "label": "Investment"
    },
    "Strategy": {
      "label": "Strategy"
    },
    "WorkDesign": {
      "label": "Work Design"
    },
    "WorkforceServices": {
      "label": "Workforce Services"
    },
    "Proposition": {
      "label": "Proposition"
    }
  },
  "lines": [
    {
      "name": "Commercial Line",
      "label": "Commercial Line",
      "color": "#FF0000",
      "shiftCoords": [0, 0],
      "nodes": [
        {
          "coords": [0, -3],
          "name": "BusEco",
          "labelPos": "NW"
        },
        {
          "coords": [3, 0],
          "name": "Sustainability",
          "labelPos": "NW"
        },
        {
          "coords": [6, 3],
          "name": "Productivity",
          "labelPos": "NW"
        },
        {
          "coords": [9, 6],
          "marker": "interchange",
          "name": "Performance",
          "labelPos": "SE"
        },
        {
          "coords": [12, 9],
          "name": "Finances",
          "labelPos": "NW"
        },
        {
          "coords": [15, 12],
          "name": "Investment",
          "labelPos": "NW"
        },
        {
          "coords": [18, 15],
          "name": "Strategy",
          "labelPos": "NW"
        }
      ]
    },
    {
      "name": "Activity Line",
      "label": "Activity Line",
      "color": "#2B8DBF",
      "shiftCoords": [0, 0],
      "nodes": [
        {
          "coords": [1, 6],
          "name": "WorkDesign",
          "labelPos": "N"
        },
        {
          "coords": [9, 6],
          "marker": "interchange",
          "name": "Performance",
          "labelPos": "E"
        }
      ]
    },
    {
      "name": "Human Line",
      "label": "Human Line",
      "color": "#85898A",
      "shiftCoords": [0, 0],
      "nodes": [
        {
          "coords": [33, 40],
          "name": "WorkforceServices",
          "labelPos": "W"
        },
        {
          "coords": [33, 38],
          "name": "Proposition",
          "labelPos": "E"
        }
      ]
    }
  ]
}
I do all my testing on d3 v5 so do let me know if you're still running into issues there.

**Comment by johnwalley** [comment]
Closing as there is no clear issue to resolve.
