### ISSUE TITLE
Question / Help - how to highlight route between 2 points on the same line

### ISSUE THREAD

**Issue by skamsie** [johnwalley/d3-tube-map#50]
I would like to be able to highlight (basically change color and width) a portion of a line between any 2 stations on the same line. Would this be a feature that could be easily added to the library, or at least give me a pointer on how to do that, thanks? 🙇

**Comment by johnwalley** [comment]
That would be a useful feature but I can't see a quick way of adding it right now.

However, you could draw a new line over the top of another to simulate the effect (different colour but same width).

<img width="438" alt="Screenshot 2019-12-17 at 11 52 48" src="https://user-images.githubusercontent.com/981531/70993643-5467f780-20c4-11ea-8cd2-69d252e5a53d.png">

Given you know which line, and which two stations need to be connected you could filter just those nodes required.

**Comment by skamsie** [comment]
@johnwalley thanks for replying, but could you add a small snippet on how to do that as I am not very familiar with `d3.js`. Let's say I know the line name `line-1` and the two stations `foo` and `bar`, how to draw a line between them?

**Comment by johnwalley** [comment]
I've put together a live example: https://codepen.io/johnwalley/pen/jOEVjey. Hope it helps

**Comment by skamsie** [comment]
It does, I appreciate it 👍 ! This is good enough for me, so I will close this ticket :)
