### ISSUE TITLE
Make nodes / stations clickable 

### ISSUE THREAD

**Issue by trenkert** [johnwalley/d3-tube-map#8]
it would be great if it was possible to click on nodes / stations as links or e.g. popups

**Comment by johnwalley** [comment]
I agree. You can already attach an event listener for click events like so

```
map.on('click', callback);
```

Rather than add popups to this project what I think I'll do is add an example of combining d3-tube-map and a popup library to achieve what you're after. I'll let you know when I've done this.

**Comment by johnwalley** [comment]
I've created an example of adding popups: https://bl.ocks.org/johnwalley/5cb483d2d63c144d2412152394f88450 @trenkert

**Comment by trenkert** [comment]
very cool, thank you!
